# Generated by Django 4.1.13 on 2024-01-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='casino_banners/')),
            ],
        ),
    ]
