# Generated by Django 4.1.13 on 2024-01-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_casinobanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casinobanner',
            options={'verbose_name_plural': 'Casino Banners'},
        ),
    ]
