# Generated by Django 4.1.13 on 2024-01-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_casinobanner_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackjackPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='blackjack_images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
