# Generated by Django 4.1.13 on 2024-01-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_blackjackpublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='casinobanner',
            name='button_position',
            field=models.CharField(choices=[('top', 'Сверху'), ('bottom', 'Снизу')], default='bottom', max_length=20),
        ),
        migrations.AddField(
            model_name='casinobanner',
            name='button_style',
            field=models.CharField(choices=[('default', 'Стандартный'), ('gold', 'Золотой')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='casinobanner',
            name='button_text',
            field=models.CharField(default='Играть сейчас', max_length=50),
        ),
        migrations.AddField(
            model_name='casinobanner',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
